# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Approved'), (2, 'Offer sent'), (3, 'Confirmed'), (4, 'Published')], default=0)),
                ('event_time', models.DateTimeField(default=None)),
                ('drafted', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('member_tickets_price', models.IntegerField()),
                ('normal_tickets_price', models.IntegerField()),
                ('slug', models.CharField(max_length=255, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Bands')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('capacity', models.IntegerField()),
                ('lease', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Stages',
                'verbose_name': 'Stage',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Stages'),
        ),
        migrations.AddField(
            model_name='events',
            name='workers',
            field=models.ManyToManyField(help_text='Members helping with this event', related_name='working_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
