# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('booking_fee', models.FloatField(default=0)),
                ('bio', models.TextField()),
                ('raider', models.TextField()),
                ('contact', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Band',
                'verbose_name_plural': 'Bands',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.IntegerField(choices=[((0,), 'Draft'), ((1,), 'Approved'), ((2,), 'Offer sent'), ((3,), 'Confirmed'), ((4,), 'Published')], default=0)),
                ('datetime', models.DateTimeField(default=None)),
                ('member_tickets_price', models.IntegerField()),
                ('normal_tickets_price', models.IntegerField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Bands')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('capacity', models.IntegerField()),
                ('lease', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Stages'),
        ),
        migrations.AddField(
            model_name='bands',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Genre'),
        ),
    ]
