# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Approved'), (2, 'Offer sent'), (3, 'Confirmed'), (4, 'Published')], default=0),
        ),
    ]
