# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='workers',
            field=models.ManyToManyField(help_text='Members helping with this event', related_name='working_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
