# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 11:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20160907_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bands',
            name='genre',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='datetime',
            new_name='event_time',
        ),
        migrations.AddField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='drafted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 7, 13, 3, 30, 914988)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 7, 13, 3, 54, 749942)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Bands'),
        ),
        migrations.DeleteModel(
            name='Bands',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
